#!/bin/bash

# This script runs 3dClustSim for each model using acf parameters generated by calculate_group_average.R

# Specify variables
# ------------------------------------------------------------------------------------------
# thresholding code directory
outputDir=/projects/dsnlab/shared/FP/FP_scripts/fMRI/fx/thresholding

# RX directories (where model masks can be found)
modelDir=/projects/dsnlab/shared/FP/nonbids_data/fMRI/rx/svc/wave1/event_noderiv

# Run 3dClustSim
# ------------------------------------------------------------------------------------------
module load afni

params=`cat ACFparameters_group_average.txt`
3dClustSim -mask "${modelDir}"/mask.nii -acf `echo "${params}"` > "${outputDir}"/3dClustStim_results.txt