#!/bin/bash
#SBATCH --job-name=3dclustsim
#SBATCH --output=3dclustsim.log
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=8G

# This script runs 3dClustSim for each model using acf parameters generated by calculate_group_average.R
# Run this script using the following command: sbatch run_3dClustSim.sh

# Specify variables
# ------------------------------------------------------------------------------------------
# thresholding code directory
outputDir=/projects/dsnlab/shared/FP/FP_scripts/fMRI/fx/thresholding

# RX directories (where model masks can be found)
modelDir=/projects/dsnlab/shared/FP/nonbids_data/fMRI/rx/svc/wave1
models=(event_noderiv illbeing_self_change social_self_change wellbeing_self_change)

# Run 3dClustSim
# ------------------------------------------------------------------------------------------
module load afni

params=`cat ACFparameters_group_average.txt`

for model in ${models[@]}; do
	echo "running $model"
	3dClustSim -mask "${modelDir}"/"${model}"/mask.nii -acf `echo "${params}"` > "${outputDir}"/3dClustStim_"${model}".txt
done
