---
title: "Himmel Demo"
author: "Dani Cosme"
date: "6/13/2018"
output: html_document
---

# load libraries
```{r}
library(tidyverse)
devtools::install_github('jflournoy/qualtrics')
```

# get post-task survey data
```{r, warning = FALSE}
# define variables
cred_file_location = '~/credentials.yaml.DEFAULT'
sid_column_name = '(SID)'
survey_name_filter = 'Himmel Survey 2018'
sid_pattern = 'HL[0-9]{3}'
exclude_sid = 'HL999' # subject IDs to exclude
identifiableData = c('IPAddress') # exclude when printing duplicates

# load credential file
credentials = scorequaltrics::creds_from_file(cred_file_location)

# filter
surveysAvail = scorequaltrics::get_surveys(credentials)
surveysFiltered = filter(surveysAvail, grepl(survey_name_filter, SurveyName))

# get survey
survey.post = scorequaltrics::get_survey_responses(credentials, 
                                               surveyid = surveysFiltered$SurveyID[[1]])

# tidy surveys
survey.post1 = survey.post %>%
  mutate(subjectID = ifelse(grepl("^[0-9]{3}", SID), paste0("HL", SID),
                     ifelse(grepl("HL[0-9]{3}", SID), SID, NA))) %>%
  filter(!subjectID == "HL999")

# check number of observations
survey.post1 %>%
  group_by(subjectID) %>%
  summarize(n = n()) %>%
  arrange(desc(n))

# filter our duplicate subject and recode condition B choices
post = survey.post1 %>%
  select(SID, CVS_2, CVS_3) %>%
  mutate(sex = ifelse(CVS_2 == "1", "female", 
                  ifelse(CVS_2 == "2", "male", CVS_2)),
         ethnicity = tolower(CVS_3),
         ethnicity = ifelse(ethnicity == "caucasian" | ethnicity == "causcasian", "caucas", ethnicity),
         nih.category = ifelse(grepl("white|wjite|caucas|middle|pakistani|hispanic|latin|mexican", ethnicity), "white",
                        ifelse(grepl("asian|chinese|japanese|korean", ethnicity), "asian",
                        ifelse(grepl("hawaiian", ethnicity), "hawaiian",
                        ifelse(grepl("black|african", ethnicity), "african american",
                        ifelse(grepl("mixed|multi|human", ethnicity), "more than one",
                        ifelse(ethnicity == "", "unknown", NA)))))),
         nih.category = ifelse(ethnicity == "white/black", "more than one",
                        ifelse(ethnicity == "asian/white", "more than one",
                        ifelse(ethnicity == "black/white", "more than one", nih.category))),
         hispanic = ifelse(grepl("hispanic|latin|mexican", ethnicity), 1, 0)) %>%
  group_by(sex, nih.category, hispanic) %>%
  summarize(n = n())
         
```
