---
title: "Specification curve"
author: "Dani Cosme"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    df_print: paged
    highlight: tango
    theme: united
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# load packages
```{r}
library(tidyverse)
library(lme4)
library(MuMIn)
library(cowplot)
```

# load data
```{r}
data.complete.spec = read.csv("data_roi.csv") %>%
  na.omit()

data.complete.spec$construct = relevel(data.complete.spec$construct, "well-being")
```

```{r}
# set na.action for dredge
options(na.action = "na.fail")

# run full model
full.model.self = lmer(percent ~ construct*self_pgACC + construct*self_vmPFC + construct*self_VS +
                       construct*self_con + construct*self_tmap +
                       (1 | subjectID), data = data.complete.spec)
full.model.selfchange = lmer(percent ~ construct*self_change_pgACC + construct*self_change_vmPFC + construct*self_change_VS +
                             construct*self_change_con + construct*self_change_tmap +
                             (1 | subjectID), data = data.complete.spec)

# run all possible nested models
models.self = dredge(full.model.self, rank = "AIC", extra = "BIC")
models.selfchange = dredge(full.model.selfchange, rank = "AIC", extra = "BIC")
all.models = bind_rows(models.self, models.selfchange) %>%
  select(AIC, delta, BIC, df, logLik, weight, `(Intercept)`, construct, everything())

# set AIC for null model you want to compare model AIC values to
null.BIC.df = all.models %>% filter(construct == "+" & df == 5)
null.BIC = null.BIC.df$BIC[1]

#saveRDS(all.models, "all_models")
#all.models = readRDS("all_models.Rds")
```

# plot
## BIC
```{r, fig.width=12, fig.height=7}
# tidy for plotting
plot.data = all.models %>%
  rename("self > change con map" = self_change_con,
         "self > change pgACC" = self_change_pgACC,
         "self > change t map" = self_change_tmap,
         "self > change vmPFC" = self_change_vmPFC,
         "self > change VS" = self_change_VS,
         "self > rest con map" = self_con,
         "self > rest pgACC" = self_pgACC,
         "self > rest t map" = self_tmap,
         "self > rest vmPFC" = self_vmPFC,
         "self > rest VS" = self_VS,
         "construct x self > change con map" = `construct:self_change_con`,
         "construct x self > change pgACC" = `construct:self_change_pgACC`,
         "construct x self > change t map" = `construct:self_change_tmap`,
         "construct x self > change vmPFC" = `construct:self_change_vmPFC`,
         "construct x self > change VS" = `construct:self_change_VS`,
         "construct x self > rest con map" = `construct:self_con`,
         "construct x self > rest pgACC" = `construct:self_pgACC`,
         "construct x self > rest t map" = `construct:self_tmap`,
         "construct x self > rest vmPFC" = `construct:self_vmPFC`,
         "construct x self > rest VS" = `construct:self_VS`) %>%
  arrange(BIC) %>%
  mutate(specification = row_number(),
         better.fit = ifelse(BIC == null.BIC, "equal", 
                      ifelse(BIC < null.BIC, "yes", "no"))) %>%
  filter(!is.na(construct) & !(delta == null.BIC.df[2,2] & df == null.BIC.df[2,4])) %>% # exclude models without construct and the duplicate null model
  mutate(specification = row_number())

# variables included in model
variable.names = names(plot.data)[8:28]

a = plot.data %>%
  ggplot(aes(specification, BIC, color = better.fit)) +
    geom_point(shape = "|", size = 4, alpha = .75) +
    geom_hline(yintercept = null.BIC, linetype = "dashed", color = "#5BBCD6") +
    scale_color_manual(values = c("#5BBCD6","black", "#F43C13")) +
    #scale_y_continuous(limits = c(2540, 2570), breaks = seq(2540, 2570, by = 10)) +
    labs(x = "", y = "BIC\n") + 
    theme_minimal(base_size = 14) +
    theme(text = element_text(family = "Futura Medium"),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 9),
          axis.text = element_text(color = "black"),
          axis.line = element_line(colour = "black"),
          legend.position = "none",
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank())

b = plot.data %>%
  gather(variable, value, eval(variable.names)) %>% 
  mutate(value = ifelse(!is.na(value), "|", ""),
         order = ifelse(grepl("self > rest VS", variable), 1,
                 ifelse(grepl("self > rest pgACC", variable), 2,
                 ifelse(grepl("self > rest vmPFC", variable), 3,
                 ifelse(grepl("self > rest con", variable), 4,
                 ifelse(grepl("self > rest t", variable), 5,
                 ifelse(grepl("self > change VS", variable), 6,
                 ifelse(grepl("self > change pgACC", variable), 7,
                 ifelse(grepl("self > change vmPFC", variable), 8,
                 ifelse(grepl("self > change con", variable), 9,
                 ifelse(grepl("self > change t", variable), 10, NA))))))))))) %>%
  ggplot(aes(specification, reorder(variable, order), color = better.fit)) +
    geom_text(aes(label = value), alpha = .75) +
    scale_color_manual(values = c("#5BBCD6","black", "#F43C13")) +
    labs(x = "\nspecification number", y = "variables\n") + 
    theme_minimal(base_size = 14) +
    theme(text = element_text(family = "Futura Medium"),
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 9),
          axis.text = element_text(color = "black"),
          axis.line = element_line(colour = "black"),
          legend.position = "none",
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank())

(plot = plot_grid(a, b, ncol = 1, align = "v"))
ggsave(plot, filename = "specification_plot_BIC.png", width = 12, height = 9, dpi = 300)
```

