---
title: "RSA_analysis"
author: "Dani Cosme"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: show
    df_print: paged
    highlight: tango
    theme: united
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999)
```

# load packages
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(gtools)
```

# define color palettes
```{r}
palette = c("white", "#FEC601", "#F43C13")
```

# source data
```{r}
source("merge_tidy_rsa.R")
```

# exclude subs
* Motion exclusions: FP091
* Technical failure: FP080, FP082
* Non-compliance: FP021, FP049, FP085, FP121
* Missing run2: FP067, FP114

```{r}
data.ex = data %>%
  filter(!subjectID %in% c("FP091", "FP080", "FP082", "FP021", "FP049", "FP085", "FP121", "FP067", "FP114"))
```

# run correlations
## primary rois
```{r, fig.width=11, fig.height=4}
data1 = data.ex %>%
  select(subjectID, run, trial, instruction, roi, voxelNum, value) %>%
  group_by(subjectID, roi, voxelNum) %>%
  mutate(trialNum = row_number()) %>%
  filter(instruction == "self") %>%
  select(-c(instruction, run, trial))

cors = data1 %>%
  group_by(subjectID, roi) %>%
  do({
    trials.spread = spread(., trialNum, value)
    cors = cor(trials.spread[,-c(1:3)], use = "pairwise.complete.obs") %>%
      as.data.frame() %>%
      mutate(subjectID = trials.spread$subjectID[[1]],
             roi = trials.spread$roi[[1]],
             trial = colnames(trials.spread)[-c(1:3)])
  })

trials.illbeing = task %>%
  filter(construct == "well-being") %>%
  select(trial) %>%
  unique() %>%
  .[,1]

trials.wellbeing = task %>%
  filter(construct == "ill-being") %>%
  select(trial) %>%
  unique() %>%
  .[,1]

trials.social = task %>%
  filter(construct == "social") %>%
  select(trial) %>%
  unique() %>%
  .[,1]

cor.plot = cors %>%
  reshape2::melt() %>%
  filter(roi %in% c("pgACC", "vmPFC", "VS")) %>%
  rename("run1" = trial,
         "run2" = variable) %>%
  mutate(run1 = as.integer(run1),
         run2 = as.integer(as.character(run2))) %>%
  filter(run1 %in% 1:36 & run2 %in% 37:72) %>%
  filter(!is.na(value)) %>%
  mutate(run2 = run2 - 36,
         run1 = ifelse(run1 %in% trials.illbeing, "ill-being",
                 ifelse(run1 %in% trials.wellbeing, "well-being",
                 ifelse(run1 %in% trials.social, "social", NA))),
         run2 = ifelse(run2 %in% trials.illbeing, "ill-being",
                 ifelse(run2 %in% trials.wellbeing, "well-being",
                 ifelse(run2 %in% trials.social, "social", NA)))) %>%
  group_by(roi, run1, run2) %>%
  mutate(fisher.z = psych::fisherz(value)) %>%
  summarize(mean.value = mean(fisher.z)) %>%
  ungroup() %>%
  mutate(run1 = ifelse(run1 == "ill-being", "ill-being run 1",
                ifelse(run1 == "well-being", "well-being run 1",
                ifelse(run1 == "social", "social run 1", run1))),
         run2 = ifelse(run2 == "ill-being", "ill-being run 2",
                ifelse(run2 == "well-being", "well-being run 2",
                ifelse(run2 == "social", "social run 2", run1)))) %>%
  ggplot(aes(run1, run2, fill = mean.value)) +
    geom_tile(color = "white") +
    scale_fill_gradientn(name = "fisher z\n", colors = palette, lim = c(0,.5), breaks = c(0, .25, .5)) + 
    geom_text(aes(label = round(mean.value,2)), size = 4, family = "Futura Medium") + 
    #geom_text(aes(label = significant), size = 4, family = "Futura Medium", nudge_x = .3, nudge_y = .2) + 
    facet_wrap(~roi, ncol = 3) +
    labs(x = "", y = "") + 
    theme_minimal(base_size = 16) +
    theme(text = element_text(family = "Futura Medium", colour = "black"),
          legend.text = element_text(size = 8),
          axis.text = element_text(color = "black"),
          axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_blank(),
          panel.background = element_blank())

ggsave(cor.plot, filename = "correlation_trial_plot.png", width = 10, height = 4.15, dpi = 300)
```

## individual rois
```{r, fig.width=11, fig.height=10}
cors %>%
  reshape2::melt() %>%
  filter(!roi %in% c("pgACC", "vmPFC", "VS")) %>%
  rename("run1" = trial,
         "run2" = variable) %>%
  mutate(run1 = as.integer(run1),
         run2 = as.integer(as.character(run2))) %>%
  filter(run1 %in% 1:36 & run2 %in% 37:72) %>%
  filter(!is.na(value)) %>%
  mutate(run2 = run2 - 36,
         run1 = ifelse(run1 %in% trials.illbeing, "ill-being",
                 ifelse(run1 %in% trials.wellbeing, "well-being",
                 ifelse(run1 %in% trials.social, "social", NA))),
         run2 = ifelse(run2 %in% trials.illbeing, "ill-being",
                 ifelse(run2 %in% trials.wellbeing, "well-being",
                 ifelse(run2 %in% trials.social, "social", NA)))) %>%
  group_by(roi, run1, run2) %>%
  summarize(mean.value = mean(value)) %>%
  #mutate(fisher.z = psych::fisherz(mean.value)) %>%
  ggplot(aes(run1, run2, fill = mean.value)) +
    geom_tile(color = "white") +
    scale_fill_gradientn(colors = c("white", "#EAC435", "#FB4D3D", "#CA1551"), lim = c(0,.5)) + 
    geom_text(aes(label = round(mean.value,2)), size = 4) + 
    facet_wrap(~roi, ncol = 3) +
    theme_minimal() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 10, hjust = 1)) +
    theme(text = element_text(size = 10))
```

## by participant
```{r, fig.width=15, fig.height=50}
cors %>%
  reshape2::melt() %>%
  filter(roi %in% c("pgACC", "vmPFC", "VS")) %>%
  rename("run1" = trial,
         "run2" = variable) %>%
  mutate(run1 = as.integer(run1),
         run2 = as.integer(as.character(run2))) %>%
  filter(run1 %in% 1:36 & run2 %in% 37:72) %>%
  filter(!is.na(value)) %>%
  mutate(run2 = run2 - 36,
         run1 = ifelse(run1 %in% trials.illbeing, "ill-being",
                 ifelse(run1 %in% trials.wellbeing, "well-being",
                 ifelse(run1 %in% trials.social, "social", NA))),
         run2 = ifelse(run2 %in% trials.illbeing, "ill-being",
                 ifelse(run2 %in% trials.wellbeing, "well-being",
                 ifelse(run2 %in% trials.social, "social", NA)))) %>%
  group_by(subjectID, roi, run1, run2) %>%
  summarize(mean.value = mean(value)) %>%
  #mutate(fisher.z = psych::fisherz(mean.value)) %>%
  ggplot(aes(run1, run2, fill = mean.value)) +
    geom_tile(color = "white") +
    scale_fill_gradientn(colors = c("#345995", "#00A1E4", "#03CEA4", "white", "#EAC435", "#FB4D3D", "#CA1551"), lim = c(-.5,.5)) + 
    geom_text(aes(label = round(mean.value,2)), size = 3) + 
    facet_wrap(~roi + subjectID, ncol = 10) +
    theme_minimal() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 10, hjust = 1)) +
    theme(text = element_text(size = 10))
```

# explore responses
```{r, fig.width=11, fig.height=4}
data1 = data.ex %>%
  select(subjectID, run, trial, instruction, roi, voxelNum, value) %>%
  group_by(subjectID, roi, voxelNum) %>%
  mutate(trialNum = row_number()) %>%
  filter(instruction == "self") %>%
  select(-c(instruction, run, trial))

cors = data1 %>%
  group_by(subjectID, roi) %>%
  do({
    trials.spread = spread(., trialNum, value)
    cors = cor(trials.spread[,-c(1:3)], use = "pairwise.complete.obs") %>%
      as.data.frame() %>%
      mutate(subjectID = trials.spread$subjectID[[1]],
             roi = trials.spread$roi[[1]],
             trial = colnames(trials.spread)[-c(1:3)])
  })

trials.illbeing = task %>%
  filter(construct == "well-being") %>%
  select(trial) %>%
  unique() %>%
  .[,1]

trials.wellbeing = task %>%
  filter(construct == "ill-being") %>%
  select(trial) %>%
  unique() %>%
  .[,1]

trials.social = task %>%
  filter(construct == "social") %>%
  select(trial) %>%
  unique() %>%
  .[,1]

responses = task %>%
  select(subjectID, run, trial, responseNum, construct, instruction) %>%
  mutate(responseNum = ifelse(responseNum == 1, "yes",
                       ifelse(responseNum == 0, "no", responseNum))) %>%
  spread(run, responseNum) %>%
  rename("resp_run1" = run1,
         "resp_run2" = run2) %>%
  group_by(subjectID) %>%
  mutate(run1 = 1:36,
         run2 = 37:72) %>%
  select(-trial) %>%
  filter(instruction == "self")
  

melted = cors %>%
  reshape2::melt() %>%
  filter(roi %in% c("pgACC", "vmPFC", "VS")) %>%
  rename("run1" = trial,
         "run2" = variable) %>%
  mutate(run1 = as.integer(run1),
         run2 = as.integer(as.character(run2))) %>%
  filter(run1 %in% 1:36 & run2 %in% 37:72) %>%
  left_join(., responses)
  filter(!is.na(value)) %>%
  mutate(run2 = run2 - 36) %>%
  mutate(
         run1 = ifelse(run1 %in% trials.illbeing, "ill-being",
                 ifelse(run1 %in% trials.wellbeing, "well-being",
                 ifelse(run1 %in% trials.social, "social", NA))),
         run2 = ifelse(run2 %in% trials.illbeing, "ill-being",
                 ifelse(run2 %in% trials.wellbeing, "well-being",
                 ifelse(run2 %in% trials.social, "social", NA)))) %>%
  group_by(roi, run1, run2) %>%
  summarize(mean.value = mean(value)) #%>%
  #mutate(fisher.z = psych::fisherz(mean.value)) %>%
  ggplot(aes(run1, run2, fill = mean.value)) +
    geom_tile(color = "white") +
    scale_fill_gradientn(colors = c("white", "#EAC435", "#FB4D3D", "#CA1551"), lim = c(0,.5)) + 
    geom_text(aes(label = round(mean.value,2)), size = 4) + 
    facet_wrap(~roi, ncol = 3) +
    theme_minimal() + 
    theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 10, hjust = 1)) +
    theme(text = element_text(size = 10))
```
