---
title: "ROC-C Analysis"
author: "Dani Cosme"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    highlight: tango
    theme: united
    toc: true
    toc_float: 
      collapsed: TRUE
      smooth_scroll: TRUE
    df_print: paged
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(error = FALSE, message = FALSE)
```

# load libraries
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(knitr)
```

# set color palettes
```{r}
palette = wesanderson::wes_palette("Zissou1", n = 4, type = "continuous")
palette_cond = wesanderson::wes_palette("Darjeeling1", 3, "continuous")
palette_grey = "#54565B"
```

# load data
```{r, warning = FALSE}
# define variables and paths
sub_dir = "~/Dropbox (PfeiBer Lab)/FreshmanProject/Tasks/ROC-C/output/FP/"
sub_pattern = "FP[0-9]{3}"
subjects = list.files(sub_dir, pattern = sub_pattern)
runs = c("run1", "run2", "run3")

# initialize data frame
data = data.frame()

# load data
for (sub in subjects) {
  for (run in runs) {
    file = paste0(sub_dir, sub, '/', sub, '_', run,'.csv')
    tmp = tryCatch(read.csv(file, stringsAsFactors = FALSE) %>%
                   mutate(subjectID = sub,
                          run = run,
                          respCue = as.integer(as.character(respCue)),
                          respRating = as.integer(as.character(respRating)),
                          respEffort = as.integer(as.character(respEffort))), error = function(e) NULL)
      data = bind_rows(data, tmp)
      rm(tmp)
  }
}
```

# tidy data
```{r}
data1 = data %>%
  filter(!subjectID %in% c("FP001", "FP999")) %>%
  mutate(rtCue = ifelse(rtCue == "NaN", NA, rtCue),
         rtRating = ifelse(rtRating == "NaN", NA, rtRating),
         rtEffort = ifelse(rtEffort == "NaN", NA, rtEffort),
         action = ifelse(respCue == 6, "look",
                  ifelse(respCue == 7, "regulate", NA)),
         action = ifelse(cond == "LOOK" & is.na(respCue), "look",
                  ifelse(cond == "REGULATE" & is.na(respCue), "regulate", action)),
         action = as.factor(action),
         choice = ifelse(cond %in% c("LOOK", "REGULATE"), "no",
                  ifelse(cond == "CHOOSE", "yes", NA)),
         choice = as.factor(choice),
         ratingDiff = respRating - likingRating) %>%
  extract(col = foodPic, into = "category", regex = "(.*)[0-9]{2}", remove = FALSE) %>%
  group_by(subjectID) %>%
  mutate(trial = row_number())
```

# missing choice data
```{r}
missing.plot = data1 %>%
  filter(choice == "yes") %>%
  group_by(subjectID, action) %>%
  summarize(n = n()) %>%
  spread(action, n) %>%
  rename("missing" = `<NA>`) %>%
  mutate(missing = ifelse(is.na(missing), 0, missing),
         missingSets = missing / 3,
         percentMissing = (missing / (look + regulate + missing)) * 100)

ggplot(missing.plot, aes(missingSets)) +
  geom_histogram(bins = 4) +
  scale_x_continuous(breaks = c(0, 1, 2, 3)) + 
  labs(x = "number of sets missing") + 
  theme_minimal()

missing.plot %>%
  ungroup() %>%
  summarize(n = n(),
            mean = mean(percentMissing, na.rm = TRUE),
            sd = sd(percentMissing, na.rm = TRUE),
            min = min(percentMissing, na.rm = TRUE),
            max = max(percentMissing, na.rm = TRUE)) %>%
      kable(digits = 2, format = "pandoc", caption = "average percent of choice trials missing")
```

# percent regulate
## all conditions
There are a few outliers, but most people chose to regulate around 50% of the time.
```{r}
percent.plot = data1 %>%
  filter(choice == "yes") %>%
  group_by(subjectID, action) %>%
  summarize(n = n()) %>%
  spread(action, n) %>%
  mutate(percent.regulate = (regulate / (look + regulate)) * 100) %>%
  arrange(percent.regulate)

ggplot(percent.plot, aes("", percent.regulate)) +
  geom_boxplot() +
  labs(x = "", y = "percent chosen to regulate") + 
  theme_minimal()

percent.plot %>%
  ungroup() %>%
  summarize(n = n(),
            mean = mean(percent.regulate, na.rm = TRUE),
            sd = sd(percent.regulate, na.rm = TRUE),
            min = min(percent.regulate, na.rm = TRUE),
            max = max(percent.regulate, na.rm = TRUE)) %>%
      kable(digits = 2, format = "pandoc", caption = "group average")

percent.plot
```

