---
title: "NV Analysis"
author: "Dani Cosme & Niko Verhoeven"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    df_print: paged
    highlight: tango
    theme: united
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(error = FALSE, message = FALSE, fig.width = 6, fig.height = 4, fig.path = "Figs/", dpi = 300, dev = "jpeg")
```

# load libraries
```{r, message=FALSE, warning=FALSE}
if (!require(tidyverse)) {
  install.packages('tidyverse')
}

if (!require(knitr)) {
  install.packages('knitr')
}

if (!require(wesanderson)) {
  install.packages('wesanderson')
}

if (!require(devtools)) {
  install.packages('devtools')
}

if (!require(scorequaltrics)) {
  devtools::install_github('jflournoy/qualtrics')
}
```

# set color palettes
```{r}
palettegreen = "#93c47d"
palette3 = c("#93C47D", "#2E6171", "#333333")
```

# EDE-QS
## get survey data
```{r, warning = FALSE}
# define variables
cred_file_location = '~/credentials.yaml.DEFAULT'
sid_column_name = '(subjectID)'
survey_name_filter = 'Freshman Project T1$'
sid_pattern = 'FP[0-9]{3}'
exclude_sid = c('FP999','999') # subject IDs to exclude
identifiableData = c('IPAddress') # exclude when printing duplicates

# load credential file
credentials = scorequaltrics::creds_from_file(cred_file_location)

# filter
surveysAvail = scorequaltrics::get_surveys(credentials)
surveysFiltered = filter(surveysAvail, grepl(survey_name_filter, SurveyName))

# get survey
surveys = scorequaltrics::get_survey_responses(credentials, 
                                               surveyid = surveysFiltered$SurveyID[[1]])

# tidy surveys
surveys1 = surveys %>%
  # select responses matching subject ID pattern
  filter(grepl(sid_pattern, subjectID)) %>%
  # exclude test responses
  filter(!subjectID %in% exclude_sid)

# check number of observations
surveys1 %>%
  group_by(subjectID) %>%
  summarize(n = n()) %>%
  arrange(desc(n))

# select relevant columns
EDEQS = surveys1 %>%
  select(subjectID, SEX, starts_with("GENDER"), starts_with("EDE")) %>%
  # score EDE-QS
  mutate_at(vars(starts_with("EDE")), as.numeric) # convert to integer

```

## score
```{r}
# calculate mean across all items
total = EDEQS %>%
  gather(EDEQS, value, starts_with("EDE")) %>%
  group_by(subjectID) %>%
  summarize(total = mean(value, na.rm = TRUE))

# calculate mean for restraint items
restrained = EDEQS %>%
  gather(EDEQS, value, starts_with("EDE")) %>%
  filter(EDEQS %in% c("EDE_QS_1", "EDE_QS_2")) %>%
  group_by(subjectID) %>%
  summarize(restrained = mean(value, na.rm = TRUE))

# calculate mean for binge items
binge = EDEQS %>%
  gather(EDEQS, value, starts_with("EDE")) %>%
  filter(EDEQS %in% c("EDE_QS_3", "EDE_QS_9", "EDE_QS_10")) %>%
  group_by(subjectID) %>%
  summarize(binge = mean(value, na.rm = TRUE))

EDEQS = left_join(EDEQS, total, by = "subjectID") %>%
  left_join(., restrained, by = "subjectID") %>%
  left_join(., binge, by = "subjectID")
```

## describe
```{r, EDEQS_describe}
EDEQS %>%
  gather(score, mean, total, restrained, binge) %>%
  ggplot(aes(score, mean)) +
    geom_boxplot() +
    geom_jitter(width = .2, alpha = .5, color = palettegreen) + 
    theme_minimal()

EDEQS %>%
  gather(score, mean, total, restrained, binge) %>%
  ggplot(aes(score, mean)) +
    geom_violin() +
    geom_jitter(width = .1, alpha = .5, color = palettegreen) + 
    theme_minimal()
```

# task
## load data
```{r, warning = FALSE}
# define variables and paths
sub_dir = "~/Dropbox (PfeiBer Lab)/FreshmanProject/Tasks/ROC-C/output/FP/"
sub_pattern = "FP[0-9]{3}"
subjects = list.files(sub_dir, pattern = sub_pattern)
runs = c("run1", "run2", "run3")

# initialize data frame
data = data.frame()

# loop through subjects and load data
for (sub in subjects) {
  for (run in runs) {
    file = paste0(sub_dir, sub, '/', sub, '_', run,'.csv')
    tmp = tryCatch(read.csv(file, stringsAsFactors = FALSE) %>%
                   mutate(subjectID = sub,
                          run = run,
                          respCue = as.integer(as.character(respCue)),
                          respRating = as.integer(as.character(respRating)),
                          respEffort = as.integer(as.character(respEffort))), error = function(e) NULL)
      data = bind_rows(data, tmp)
      rm(tmp)
  }
}
```

## tidy data
```{r}
task = data %>%
  # exclude FP001 and FP999
  filter(!subjectID %in% c("FP001", "FP999")) %>%
  # recode values
  mutate(rtCue = ifelse(rtCue == "NaN", NA, rtCue), # NaN as NA
         rtRating = ifelse(rtRating == "NaN", NA, rtRating), # NaN as NA
         rtEffort = ifelse(rtEffort == "NaN", NA, rtEffort), # NaN as NA
         action = ifelse(respCue == 6, "look", # cue button presses
                  ifelse(respCue == 7, "regulate", NA)),
         action = ifelse(cond == "LOOK" & is.na(respCue), "look", # missing cue button presses
                  ifelse(cond == "REGULATE" & is.na(respCue), "regulate", action)),
         action = as.factor(action), # change to factor
         choice = ifelse(cond %in% c("LOOK", "REGULATE"), "no", # choice values
                  ifelse(cond == "CHOOSE", "yes", NA)),
         choice = as.factor(choice), # change to factor
         respRating = respRating - 5, # recode button box presses to 1-4 scale
         respRating = as.integer(respRating), # change to integer
         respEffort = respEffort - 5, # recode button box presses to 1-4 scale
         respEffort = as.integer(respEffort)) %>% # change to integer
  # add trial number
  group_by(subjectID) %>%
  mutate(trial = row_number()) %>%
  # reorder columns
  select(subjectID, run, trial, action, choice, cond, respCue, everything()) %>%
  ungroup()
```

## calculate reg. success
```{r}
reg.success = task %>%
  # remove missing data
  filter(!is.na(action)) %>%
  # group by subject and calculate mean
  group_by(subjectID, action) %>%
  summarize(mean = mean(respRating, na.rm = TRUE)) %>%
  # calculate regulation success
  spread(action, mean) %>%
  mutate(reg.success = look - regulate)
```

## describe reg. success
```{r, reg.success_describe}
reg.success %>%
  gather(score, mean, look, regulate, reg.success) %>%
  ggplot(aes(score, mean)) +
    geom_boxplot() +
    geom_jitter(width = .2, alpha = .5, color = palettegreen) + 
    theme_minimal()

reg.success %>%
  gather(score, mean, look, regulate, reg.success) %>%
  filter(score == "reg.success") %>%
  mutate(score = ifelse(score == "reg.success", "reappraisal ability", score)) %>%
  ggplot(aes(score, mean)) +
    geom_boxplot() +
    geom_jitter(width = .2, alpha = .5, color = palettegreen) + 
    theme_minimal()

reg.success %>%
  gather(score, mean, look, regulate, reg.success) %>%
  ggplot(aes(score, mean)) +
    geom_violin() +
    geom_jitter(width = .1, alpha = .5, color = palettegreen) + 
    theme_minimal()
```

## plot reg. success
```{r, reg.success}
reg.success %>%
  gather(action, mean, look, regulate) %>%
  ggplot(aes(action, mean)) +
    geom_point(aes(group = subjectID), color = palettegreen, alpha = .1, size = 3) + 
    geom_line(aes(group = subjectID), color = palettegreen, alpha = .1, size = 1) + 
    stat_summary(aes(group = 1), color = palettegreen, fun.y = mean, geom = "line", size = 2) +
    stat_summary(color = palettegreen, fun.data = "mean_cl_boot", size = 1.5) +
    labs(y = "mean craving rating") + 
    theme_minimal()

task %>%
  filter(!is.na(action)) %>%
  group_by(action) %>%
  summarize(mean = mean(respRating, na.rm = TRUE),
            sd = sd(respRating, na.rm = TRUE),
            n = n()) %>%
  kable(digits = 2, format = "pandoc", caption = "craving ratings")
```

## calculate mean effort
```{r}
effort = task %>%
  filter(action == "regulate") %>%
  group_by(subjectID) %>%
  summarize(meanEffort = mean(respEffort, na.rm = TRUE))
```

## describe effort
```{r, effort_describe}
effort %>%
  gather(score, mean, meanEffort) %>%
  mutate(score = ifelse(score == "meanEffort", "effort", score)) %>%
  ggplot(aes(score, mean)) +
    geom_boxplot() +
    geom_jitter(width = .2, alpha = .5, color = palettegreen) + 
    theme_minimal()

effort %>%
  gather(score, mean, meanEffort) %>%
  mutate(score = ifelse(score == "meanEffort", "effort", score)) %>%
  ggplot(aes(score, mean)) +
    geom_violin() +
    geom_jitter(width = .1, alpha = .5, color = palettegreen) + 
    theme_minimal()
```

# correlations
```{r}
# merge data
merged = left_join(reg.success, EDEQS, by = "subjectID") %>%
  left_join(., effort, by = "subjectID")
```

## reg. success
Example stats reporting format:
_r_ = .19, 95% CI = [-.077, .44], _t_(51) = 1.44, _p_ = .156 

```{r}
# total
cor.test(merged$reg.success, merged$total)

# restrained
cor.test(merged$reg.success, merged$restrained)

# binge
cor.test(merged$reg.success, merged$binge)
```

## effort
```{r}
# total
cor.test(merged$meanEffort, merged$total)

# restrained
cor.test(merged$meanEffort, merged$restrained)

# binge
cor.test(merged$meanEffort, merged$binge)
```

# plot correlations
## reg. success
```{r, reg.success_correlation}
merged %>%
  gather(score, mean, total, restrained, binge) %>%
  ggplot(aes(mean, reg.success)) + 
    geom_point(color = palettegreen, alpha = .5) +
    geom_smooth(method = "lm", color = palettegreen, size = 2) + 
    facet_grid(~score) +
    labs(x = "mean score", y = "reappraisal ability (look- regulate)") +
    theme_minimal()

merged %>%
  gather(score, mean, total, restrained, binge) %>%
  ggplot(aes(mean, reg.success, color = score)) + 
    geom_point(alpha = .5) +
    geom_smooth(method = "lm", alpha = .2, size = 1.5) + 
    scale_color_manual(values = palette3) +
    labs(x = "mean score", y = "reappraisal ability (look- regulate)") +
    theme_minimal()
```

## effort
```{r, effort_correlation}
merged %>%
  gather(score, mean, total, restrained, binge) %>%
  ggplot(aes(mean, meanEffort)) + 
    geom_point(color = palettegreen, alpha = .5) +
    geom_smooth(method = "lm", color = palettegreen, size = 2) + 
    facet_grid(~score) +
    labs(x = "mean score", y = "mean effort rating") +
    theme_minimal()

merged %>%
  gather(score, mean, total, restrained, binge) %>%
  ggplot(aes(mean, meanEffort, color = score)) + 
    geom_point(alpha = .5) +
    geom_smooth(method = "lm", alpha = .2, size = 1.5) + 
    scale_color_manual(values = palette3) +
    labs(x = "mean score", y = "mean effort rating") +
    theme_minimal()
```
